/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_scut_dongxia_hazeremove_dehaze_DeHaze */

#ifndef _Included_cn_scut_dongxia_hazeremove_dehaze_DeHaze
#define _Included_cn_scut_dongxia_hazeremove_dehaze_DeHaze
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_scut_dongxia_hazeremove_dehaze_DeHaze
 * Method:    n_createHazeRemoveModel
 * Signature: (IDDDII)V
 */
JNIEXPORT void JNICALL Java_cn_scut_dongxia_hazeremove_dehaze_DeHaze_n_1createHazeRemoveModel
        (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     cn_scut_dongxia_hazeremove_dehaze_DeHaze
 * Method:    n_deleteHazeRemoveModel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_scut_dongxia_hazeremove_dehaze_DeHaze_n_1deleteHazeRemoveModel
        (JNIEnv *, jclass);

/*
 * Class:     cn_scut_dongxia_hazeremove_dehaze_DeHaze
 * Method:    n_videoHazeRemove
 * Signature: ([BIJ)V
 */
JNIEXPORT void JNICALL Java_cn_scut_dongxia_hazeremove_dehaze_DeHaze_n_1videoHazeRemove
        (JNIEnv *, jclass, jbyteArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
