/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_scut_dongxia_hazeremove_dehaze_DeHaze */

#ifndef _Included_cn_scut_dongxia_hazeremove_dehaze_DeHaze
#define _Included_cn_scut_dongxia_hazeremove_dehaze_DeHaze
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_scut_dongxia_hazeremove_dehaze_DeHaze
 * Method:    n_createHazeRemoveModel
 * Signature: (IDDD)V
 */
JNIEXPORT void JNICALL Java_cn_scut_dongxia_hazeremove_dehaze_DeHaze_n_1createHazeRemoveModel
        (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble);

/*
 * Class:     cn_scut_dongxia_hazeremove_dehaze_DeHaze
 * Method:    n_deleteHazeRemoveModel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_scut_dongxia_hazeremove_dehaze_DeHaze_n_1deleteHazeRemoveModel
        (JNIEnv *, jclass);

/*
 * Class:     cn_scut_dongxia_hazeremove_dehaze_DeHaze
 * Method:    n_estimateAtmosphericLight
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_cn_scut_dongxia_hazeremove_dehaze_DeHaze_n_1estimateAtmosphericLight
        (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_scut_dongxia_hazeremove_dehaze_DeHaze
 * Method:    n_estimateTramsmission
 * Signature: (J[FJ)V
 */
JNIEXPORT void JNICALL Java_cn_scut_dongxia_hazeremove_dehaze_DeHaze_n_1estimateTramsmission
        (JNIEnv *, jclass, jlong, jfloatArray, jlong);

/*
 * Class:     cn_scut_dongxia_hazeremove_dehaze_DeHaze
 * Method:    n_recover
 * Signature: (JJ[FJ)V
 */
JNIEXPORT void JNICALL Java_cn_scut_dongxia_hazeremove_dehaze_DeHaze_n_1recover
        (JNIEnv *, jclass, jlong, jlong, jfloatArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
